### ISSUE TITLE
Not possible to run migration when using AbstractUser

### ISSUE THREAD

**Issue by kunambi** [madssj/django-longer-username-and-email#12]
I assume that this error appears since I'm extending User with AbstractUser.

```
(env) C:\xampp\htdocs\woe>python manage.py migrate longerusernameandemail
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    django.setup()
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\apps\registry.py", line 115, in populate
    app_config.ready()
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\contrib\admin\apps.py", line 22, in ready
    self.module.autodiscover()
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\utils\module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\xampp\htdocs\woe\env\lib\site-packages\longerusernameandemail\admin.py", line 19, in <module>
    admin.site.unregister(User)
  File "C:\xampp\htdocs\woe\env\lib\site-packages\django\contrib\admin\sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model User is not registered
```

**Comment by madssj** [comment]
I'm really not maintaining this anymore, but what django version are you trying to run it with?

**Comment by kunambi** [comment]
Hi,

Using latest django version 1.9.6:

```
>>> import django
>>> django.VERSION
(1, 9, 6, 'final', 0)
```

**Comment by madssj** [comment]
You shouldn't use this package with newer django versions. Any particular reason you'd like to use it with 1.9?
